### ISSUE TITLE
Improve documentation/wiki

### ISSUE THREAD

**Issue by vintharas** [googleads/angular-dfp#1]

**Comment by rmsween** [comment]
Hey, in lieu of full documentation do you think you could you provide some super basic getting started tips? I've downloaded the npm repo and saved it to my angular project, but I'm not sure how to go about importing it into my app.module, or using it within a component.

Sorry if this is a newb question.

**Comment by vintharas** [comment]
Hi @rmsween ! 

Sorry for the lack of documentation. We're working on providing a quickstart as soon as possible.

In the meantime you can take a look at this [jsbin](http://jsbin.com/nefecujala/edit?html,js,console,output) that shows the minimum setup required to run this library in your angular app.

**Comment by vintharas** [comment]
Wop! Looks like jsbin is misbehaving today and refused to save the example. [This is the good one](http://jsbin.com/wiwuvow/edit?html,js,output).

**Comment by vintharas** [comment]
https://github.com/googleads/angular-dfp/wiki/Getting-Started

**Comment by rmsween** [comment]
@Vintharas Thank you very much for the quick reply and the steps! They worked great for me.

**Comment by vintharas** [comment]
Awesome! :) Glad to help! ^^
