### ISSUE TITLE
Ads is opened in the same iframe for Android 4.4.2

### ISSUE THREAD

**Issue by anouarcharif** [googleads/angular-dfp#11]
Hello,

Im facing an issue with your plugin that im using with my ionic project.

The ads show perfectly, but when i click on it, the target is opened in the same iframe of the the ads content ... i already have target="_blank" as a configuration for all my ads slots.

Do you have any idea, how can i solve this .?

Thank you

**Comment by ChristiaanScheermeijer** [comment]
Hi @anouarcharif, since you are using a Cordova/Ionic application it is not allowed to open external pages. You can use [cordova-plugin-inappbrowser](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-inappbrowser/) to open ad targets in the user's system browser.

**Comment by anouarcharif** [comment]
Hi @ChristiaanScheermeijer, i have other links in my app with external link, and they all opened in the user's system browser. The issue concern only the click on the ads generated.

Thank you
