### ISSUE TITLE
Add minified bundle to NPM or bower

### ISSUE THREAD

**Issue by nosovk** [googleads/angular-dfp#4]
It would be nice to download minified version not from demo site, but from NPM.

**Comment by antonyjseven** [comment]
Got the same problem today, and added it to NPM cause nobody acted.
But it didn't helped me a lot. I don't see ad anyway.
[Link to NPM](https://www.npmjs.com/package/angular-dfp)
`npm install angular-dfp`

**Comment by goldsborough** [comment]
Thanks for adding it! Sorry we didn't respond faster.

**Comment by vintharas** [comment]
Hi guys! ^_^

Our intention was to complete the documentation and write a thorough suite of tests before releasing it on npm.
