### ISSUE TITLE
dfp not loaded

### ISSUE THREAD

**Issue by antonyjseven** [googleads/angular-dfp#5]
I try to use <dfp-ad> directive. Small code sample:
```
<dfp-ad force-safe-frame ad-unit="/20424919247/300x600" id="div-gpt-ad-1491998315536-2">
  <dfp-size width="300" height="600"></dfp-size>
</dfp-ad>
```
Directives are loaded, but probably dfp libararry is broken.  Problem cmd.push method - functions passed to it never executed. Like:
`googletag.cmd.push(setup);` (dfp.js:232)
which shoul add `setup `function into thr queue for launching after dfp initialization, but in common `setup `never launched

**Comment by goldsborough** [comment]
Not sure I quite understand. Have you looked at the demo code? Or did you notice anything suspicious on the console?

**Comment by vintharas** [comment]
Hi guys! ^_^

[Here you have an example on jsbin](http://jsbin.com/herarez/edit?html,js,output) using the angular-dfp version that you've uploaded to npm.

Could you a provide a jsbin or similar so we can reproduce your error?
