### ISSUE TITLE
dfpResponsive broken in Angular 1.6.4

### ISSUE THREAD

**Issue by ChristiaanScheermeijer** [googleads/angular-dfp#9]
The `viewportWidth` and `viewportHeight` scope properties are always undefined on controller instantiation. This results in the invalid SingleSizeArray of `[undefined, 0]` passed to the defineSizeMapping function.

**Suspect:** 
https://github.com/googleads/angular-dfp/blob/master/src/dfp/dfp-responsive.js#L67

**Warning from googletag:**

> Incorrect usage of googletag.Slot defineSizeMapping: Size mapping has to be an array

**Code used:**

```
<dfp-ad collapse-if-empty ad-unit="/123457/unit">
  <dfp-size width="300" height="250"></dfp-size>
  <dfp-responsive viewport-width="0" viewport-height="0">
    <dfp-size width=300 height=250></dfp-size>
  </dfp-responsive>
  <dfp-responsive viewport-width="768" viewport-height="0">
    <dfp-size width=728 height=90></dfp-size>
  </dfp-responsive>
</dfp-ad>
```

**Comment by RWOverdijk** [comment]
:+1: :)
